version: '2'

services:
  ntsparksearch:
    image: arananegra/ntsparksearch:1.0.0nc
    restart: always
    extra_hosts:
      - "database:172.16.239.11"
      - "redis-server:172.16.239.12"
    networks:
      ci_co_net:
        ipv4_address: 172.16.239.10
    container_name: ntsparksearch_docker
    ports:
      - 5000:5000
    links:
      - mongodb_ntsparksearch:ntsparksearch_docker
      - redis:ntsparksearch_docker
      - worker-rq:ntsparksearch_docker
      - ntsparksearch_frontend:ntsparksearch_docker
    volumes:
      - ./volumes/input_files:/usr/spark-2.1.0/input
      - ./volumes/output_files:/usr/spark-2.1.0/output
    command: python3.4 /usr/spark-2.1.0/ntsparksearch_backend/ntsparksearch/RestApi/ServiceRunner.py
  
  mongodb_ntsparksearch:
    image: mongo:3.4.6
    container_name: mongodb_ntsparksearch
    networks:
      ci_co_net:
        ipv4_address: 172.16.239.11
    mem_limit: 256m
    ports:
      - 8082:27017
    volumes:
      - ./volumes/mongodb_recovery:/data/db
    restart: always

  worker-rq:
    image: arananegra/ntsparksearch:1.0.0nc
    networks:
      ci_co_net:
        ipv4_address: 172.16.239.13
    extra_hosts:
      - "database:172.16.239.11"
      - "redis-server:172.16.239.12"
    container_name: ntsparksearch_docker_worker-rq
    command: python3.4 /usr/spark-2.1.0/ntsparksearch_backend/ntsparksearch/RestApi/worker.py 
    links:
      - redis:ntsparksearch_docker_worker-rq
    depends_on:
    - redis

  redis:
    image: redis:3.2.8
    command: redis-server
    networks:
      ci_co_net:
        ipv4_address: 172.16.239.12
    ports:
      - 6379:6379
    container_name: redis_ntsparksearch
    restart: always
  
  ntsparksearch_frontend:
    image: arananegra/ntsparksearch_frontend:1.0.0
    restart: always
    networks:
      ci_co_net:
        ipv4_address: 172.16.239.14
    ports:
      - 1313:8080
    container_name: ntsparksearch_frontend_docker

networks:
  ci_co_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.2

    
